name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72
        with:
          extra_nix_config: sandbox = true

      - name: Build
        run: ./build.sh

      - name: Deploy on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.4
        with:
          folder: dist
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository-name: zopieux/zopieux.github.io
          branch: master
          target-folder: stlsvg
          commit-message: Deploy stlsvg.
          git-config-user: Alexandre Macabies
          git-config-email: <web+oss@zopieux.com>
